### ISSUE TITLE
make the makefile under tf1.14-gpu and cuda9.0

### ISSUE THREAD

**Issue by ChangMingCS** [TonythePlaneswalker/pcn#16]
i modified the path like blow:
cuda_inc = /usr/local/cuda-9.0/include/
cuda_lib = /usr/local/cuda-9.0/lib64/
nsync = /home/XXX/anaconda3/lib/python3.6/site-packages/tensorflow/include/external/nsync/public
nvcc = /usr/local/cuda-9.0/bin/nvcc
tf_inc = /home/XXX/anaconda3/lib/python3.6/site-packages/tensorflow/include
tf_lib = /home/XXX/anaconda3/lib/python3.6/site-packages/tensorflow

but when i run the make ,it occured：
make: Circular tf_nndistance.cu <- tf_nndistance.cu.o dependency dropped.
make: Circular tf_approxmatch.cu <- tf_approxmatch.cu.o dependency dropped.
make: Nothing to be done for 'all'.

if the code could work under my configuration environment? and how to fix it?

**Comment by ChangMingCS** [comment]
i have fixed it, i should rm the .so.so files and let it make them again.

**Comment by StevenZzz07** [comment]
Hello, recently i am working on reproducing this PCN. My environment is windows10+Tensorflow1.13.1+cuda10.0.  However, when i follow the instructions to build the .c & .cu code under pc_distance directory using make, i am caught up with a compiling bug as follows:
`cannot find -ltensorflow_framework \ collect2.exe: error: ld returned 1 exit status`

And i modified the makefile path as follows:
cuda_inc = "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include/"
cuda_lib = "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/"
nvcc = "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/bin/nvcc"
tf_inc1 = "D:/Anaconda3/envs/pcn/Lib/site-packages/tensorflow/include" 
tf_inc2 = "D:/Anaconda3/envs/pcn/Lib/site-packages/tensorflow/include/google/protobuf_archive/src" 
tf_inc3 = "D:/Anaconda3/envs/pcn/Lib/site-packages/tensorflow/include/tensorflow/include/external/com_google_absl" 
tf_inc4 = "D:/Anaconda3/envs/pcn/Lib/site-packages/tensorflow/include/third_party/eigen3" 
tf_inc5 = "D:/Anaconda3/envs/pcn/Lib/site-packages/tensorflow/include/tensorflow/include/external/eigen_archive"
tf_lib1 = "D:/Anaconda3/envs/pcn/Lib/site-packages/tensorflow"
tf_lib2 = "D:/Anaconda3/envs/pcn/Lib/site-packages/tensorflow/include/tensorflow/core/lib"
tf_lib3 = "D:/Anaconda3/envs/pcn/Lib/site-packages/tensorflow/include/tensorflow/stream_executor/lib"

So i was wondered whether it is my wrong path assignment that results in my bug or any other mistakes.  So could you share me with your successful path assignment? Or maybe the difference between TensorFlow version counts since yours is 1.14 and mine is 1.13.  Any helpful advice is greatly appreciated!

Thanks a lot!
